/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'antonorn' at '10/30/14 1:14 PM' with Gradle 2.1
 *
 * @author antonorn, @date 10/30/14 1:14 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
